version: '3.9'
services:
  admin-panel:
    image: gamehub-admin:latest  # Ensure this image is built and pushed to a registry
    ports:
      - "3001" 
    volumes:
      - .:/app  # This will not work in Swarm mode; consider using a different approach for persistent storage
    environment:
      - NODE_ENV=development
    networks:
      - gamehub-network  # Use the overlay network

networks:
  gamehub-network:
    external: true
